name: Execute simple node webapp app
run-name: Execute simple node webapp on push to ${{ github.ref }}
on:
  push:
    branches: ['main', 'develop']

jobs:
  Build-Simple-Webapp:
    uses: harrysince1992/simple-cicd-pipeline/.github/workflows/CI-trigger.yml@main
    secrets: inherit
        
