name: Execute simple node webapp app
run-name: Execute simple node webapp on push to ${{ github.ref }}
on:
  push:
    branches: ['main', 'develop']

jobs:
  Build-simple-webapp:
    name: Build simple node webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date and time format
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - name: echo current date and time
        run: echo ${{ steps.date.outputs.date }}
      - name: setup latest app version
        if: ${{ github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/develop' }}
        run: |
          if [[ ${{ github.event.ref }} == 'refs/heads/main' ]];then
            echo "It is main branch. hence, we will create release tag"
          elif [[ ${{ github.event.ref }} == 'refs/heads/develop' ]];then
             echo "It is main branch. hence, we will create snapshot tag"
          fi
      # - name: push latest image
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: l
        
